### ISSUE TITLE
Implementing the theme

### ISSUE THREAD

**Issue by testprepturkey** [biggerbluebutton/bigbluebutton_modern_UI#1]
Hi,

I appreciate your work and I want to implement it in my setup. Does it require too much coding? I am unfamiliar with API Join Method?

Thank you!

**Comment by biggerbluebutton** [comment]
sorry for late response. 
which front-end client you're using ?
in case of greenlight then I don't know how to implement it 

you can test the plugin directly on your website: https://biggerbluebutton.com 
just go there and create new account and join to any room

in fact we have already made this theme the default for our platform

**Comment by testprepturkey** [comment]
Thank hou very much for the reply.
I am using html5 client.

**Comment by biggerbluebutton** [comment]
yes I know but which front-end app you're accessing your bigbluebutton from ?
moodle or greenlight or canvas ? etc.

**Comment by testprepturkey** [comment]
Wordpress

**Comment by biggerbluebutton** [comment]
you have to modify wordpress bigbluebutton plugin from the core files and add new parameter (bbb_custom_style_url)
