### ISSUE TITLE
Use php API to add extra Parameters

### ISSUE THREAD

**Issue by magnaapps** [biggerbluebutton/bigbluebutton_modern_UI#2]
How can i implement this to add extra parameters when using JoinMeetingParameters() PHP API?

**Comment by biggerbluebutton** [comment]
apologize for late response
you have to pass it as custom parameter to your PHP API 
the parameter name is bbb_custom_style_url
pass it to join API request

**Comment by magnaapps** [comment]
Thank you, managed to add the following using the php API:
$customData = ['userdata-bbb_custom_style_url' => 'https://linktomydomain/themes/modern.css'];
